version: '3.9'

services:
  server:
    ports:
      - 5000:5333
    container_name: topnews-api
    networks:
      - nginxproxymanager_default
    restart: always
    build: .

networks:
  nginxproxymanager_default:
    external: true