version: '3.9'

services:
  server:
    ports:
      - 5333:5000
    container_name: topnews-api
    networks:
      - nginx-proxy-manager_default
    restart: always
    env_file:
      - .env
    build: .

networks:
  nginx-proxy-manager_default:
    external: true
