version: '3.9'

services:
  server:
    ports:
      - 5333:5000
    container_name: topnews-api
    networks:
      - nginxproxymanager_default
    restart: always
    env_file:
      - .env
    build: .

networks:
  nginxproxymanager_default:
    external: true
